INSERT INTO producto (id, categoria_id, nombre, stock, precio) VALUES (1, 1, 'Martillo Mediano', 50, 6200);
INSERT INTO producto (id, categoria_id, nombre, stock, precio) VALUES (2, 2, 'Destornillador Phillips Largo', 100, 3900);
INSERT INTO producto (id, categoria_id, nombre, stock, precio) VALUES (3, 2, 'Llave Inglesa 25mm', 50, 21500);
INSERT INTO producto (id, categoria_id, nombre, stock, precio) VALUES (4, 3, 'Sierra Circular 600HP', 10, 214200);
INSERT INTO producto (id, categoria_id, nombre, stock, precio) VALUES (5, 4, 'Cinta Métrica 5 M', 50, 5000);
INSERT INTO producto (id, categoria_id, nombre, stock, precio) VALUES (6, 5, 'Tornillo Para Madera Autoperforante', 10000, 10);
INSERT INTO producto (id, categoria_id, nombre, stock, precio) VALUES (7, 6, 'Tuerca M8', 10000, 225);
INSERT INTO producto (id, categoria_id, nombre, stock, precio) VALUES (8, 7, 'Serrucho de Carpintero 25mm', 50, 16900);
INSERT INTO producto (id, categoria_id, nombre, stock, precio) VALUES (9, 5, 'Clavos De 2 1/2\" Caja 5 Kg', 10, 12000);
INSERT INTO producto (id, categoria_id, nombre, stock, precio) VALUES (10, 8,'Cadena de Acero x 1 M', 10, 1200);
INSERT INTO producto (id, categoria_id, nombre, stock, precio) VALUES (11, 6, 'Tornillo Hexagonal M10', 10000, 56);
